### ISSUE TITLE
Test failed in copr

### ISSUE THREAD

**Issue by ghost** [kvark/obj#30]
https://download.copr.fedorainfracloud.org/results/remilauzier/rust-simp/fedora-rawhide-x86_64/02251171-rust-obj/builder-live.log.gz

Some test failed in copr.

**Comment by kvark** [comment]
```
---- round_trip_sponza_with_mtl stdout ----
thread 'round_trip_sponza_with_mtl' panicked at 'called `Result::unwrap()` on an `Err` value: Io(Os { code: 2, kind: NotFound, message: "No such file or directory" })', tests/round_trip.rs:30:63
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace

---- round_trip_sponza_no_mtls stdout ----
thread 'round_trip_sponza_no_mtls' panicked at 'called `Result::unwrap()` on an `Err` value: Io(Os { code: 2, kind: NotFound, message: "No such file or directory" })', tests/round_trip.rs:19:59
```
